### ISSUE TITLE
When will the complete code be released？

### ISSUE THREAD

**Issue by tb2-sy** [zju3dv/Vox-Surf#1]
dear authors:
very nice work!
When will the complete code be released? thanks.

**Comment by garylidd** [comment]
Hi, thank you for your attention to our work. 
I'm dealing with graduation related matters recently. The complete code is expected to be open source in early February next year. If you need experimental results for comparison please contact me via garyli@zju.edu.cn.

**Comment by tb2-sy** [comment]
> Hi, thank you for your attention to our work. I'm dealing with graduation related matters recently. The complete code is expected to be open source in early February next year. If you need experimental results for comparison please contact me via [garyli@zju.edu.cn](mailto:garyli@zju.edu.cn).

Thank you for your reply, and happy graduation!

**Comment by shawnsya** [comment]
Hi! Very nice work!
When will the code be released?
Thanks a lot.
